### ISSUE TITLE
Calendar Coordinator not active

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#10]
The Calendar Coordinator of a club does not have to have an active Range Badge.  I get "No Active Member Found" when trying to add to Auth Users.

**Comment by tdasto** [comment]
But, I was able to over write First Name and create.

**Comment by sharkbit** [comment]
All users were suppose to have active badges, except Root.  You can create an account as a root user with a password then change their permissions.  Make sure to change their username to the desired level before creation as root.
