### ISSUE TITLE
Remove RSO Permissions Badge #7439

### ISSUE THREAD

**Issue by THyatt1** [sharkbit/BadgeApp#100]
Peter Tarley, badge #7439 is no longer a RSO. He does not need RSO permissions. Peter is a current badge holder.

**Comment by sharkbit** [comment]
yo should be able to remove the RSO permissions from him and it will be fine.  Normal members don't have user accounts.

Is the Red Message to scary?  Should it say something else?   'User account will be deleted and user will be converted to Normal Member' ?

**Comment by THyatt1** [comment]
Ok. I just remember the last time I did it, I broke something.

**Comment by sharkbit** [comment]
If it worked and you are Happy, you can close the ticket with the Close button On Github!  Plz :)
