### ISSUE TITLE
Broken on Viewing Range Violation

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#106]
Trying to leave the right info for you;

.../violations/index?ViolationsSearch%5Bbadge_reporter%5D=&ViolationsSearch%5Bvi_type%5D=&ViolationsSearch%5Bbadge_involved%5D=7963&ViolationsSearch%5Bvi_rules%5D=&ViolationsSearch%5Bwas_guest%5D=&ViolationsSearch%5Bvi_loc%5D=&ViolationsSearch%5Bvi_date%5D=

![image](https://user-images.githubusercontent.com/67211480/95679443-e172c480-0ba0-11eb-8fd9-a7af25678935.png)

**Comment by sharkbit** [comment]
Evidently the PHP implode function use to be able to take the "glue" on ether side for it's parameters.  but they stopped that,  this was the only place in the project.  
- Fixed
