### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#11]
Change Delete dropdown menu to a Delete button

**Comment by sharkbit** [comment]
What?  Where?  Pretend  I have no Idea what your talking about. This is a very sad ticket.

**Comment by tdasto** [comment]
Try to delete an event by opening the event first. Drop down in the event
called Delete. Has YES or NO in the drop down. Could change to a button
instead to delete.

**Comment by sharkbit** [comment]
I will change it to:
  Calendar event,  if has permission show delete button, or 'deleted', else show status only

**Comment by sharkbit** [comment]
[Fixed event delete button](https://github.com/sharkbit/BadgeApp/commit/c387113b271d6cd0d74876295ffa932a6e6e4c24)
