### ISSUE TITLE
Membership Type Discrepancy; Staff

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#119]
Andrew noticed that Range Badge Holders listed when Membership Type = Staff is selected in Range Badge list does not jive with the actual staff list. Names of Staff BH's are listed that are no longer on staff and many RSOs are not listed under Staff. 

Here is what is happening; staff members that are not members of a club get Club Name = Associated Gun Clubs Staff and Badge Type = Staff while staff members that are members get their correct club name and their purchased badge type then also get the RSO privilege.

**Comment by sharkbit** [comment]
Umm....  is there a code issue?  this sounds like a procedural issue?  
- When giving RSO permissions make sure member is also added to AGC staff.
- And if they are no longer an RSO  remove there permissions

Do we need to discuss this?

**Comment by tdasto** [comment]
Yes, we do. You cannot do your first bullet which makes your second bullet irrelevant.

**Comment by tdasto** [comment]
Membership Type Column in AGC App needs to be Badge Type like we did yesterday. Didn't you push the change?

**Comment by sharkbit** [comment]
This will need some testing, but it seems to work.  
- If you add a new RSO or Lead RSO they will be added to Staff,
- Removing that privilege will remove staff and if they have no other clubs they go into 'Z old data'.

**Comment by tdasto** [comment]
This does not work at all.
