### ISSUE TITLE
Delete Trash Can

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#12]
Add trash can to Action column to all Calendar Coordinators (not CIOs)

**Comment by sharkbit** [comment]
Fixed [here](https://github.com/sharkbit/BadgeApp/commit/2308e2b031deaf2480b8ee4d0d54709518572d58)

**Comment by tdasto** [comment]
Trash can icon does not work for 02 50 3870 4x

**Comment by sharkbit** [comment]
[Fixed event delete button](https://github.com/sharkbit/BadgeApp/commit/c387113b271d6cd0d74876295ffa932a6e6e4c24)
