### ISSUE TITLE
AS RSO Badge Option

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#120]
Andrew has asked for an option to print out an Action Shooting RSO badge. The BH's who have this badge do **not** need special App privileges. The badge should look like the RSO badge but say Action RSO or Action Shooting RSO on it along with the persons name and regular badge number.

**Comment by sharkbit** [comment]
How is this: 
![action](https://user-images.githubusercontent.com/979670/103283641-1b38b780-49a7-11eb-88d8-8feac0ad52ff.jpg)

**Comment by tdasto** [comment]
Yes, looks great if that is the badge number also.

I wanted to talk about this issue, too. I'm around if you want to Skype.
