### ISSUE TITLE
Guest Error

### ISSUE THREAD

**Issue by JennMart** [sharkbit/BadgeApp#122]
The dollar amount under amount due is not populating when someone tries to sign in a guest.  When trying to process the transaction via credit card now it states an error. There is a "work around" that works when you change the quantity to a random number then the amount due shows, then you have to switch the quantity of guests to the correct number.

**Comment by sharkbit** [comment]
Updated guest form to have a default of 1 guest and payment method of cash.

**Comment by tdasto** [comment]
Just an FYI - the Guest computer is not setting the dollar value to null like on TMPapp when you select Spouse or Minor.

Another potential issue with the form; if you accidentally click Spouse (or Minor) the dollar value goes blank (on TMPapp) but then click Shooter and the dollar value stays blank...

**Comment by sharkbit** [comment]
Think I fixed it now.
