### ISSUE TITLE
badge number in store

### ISSUE THREAD

**Issue by JennMart** [sharkbit/BadgeApp#124]
RSOs report that the badge number box in the store does not allow anything to be entered.  To work around they have to check the guest box and have it automatically add the 9999 number for guests and then when the box is unchecked they can enter the badge number of the person making the purchase.  I have not noticed this on the badge sales computer but it is happening on the guest station one computer.  They were able to duplicate this to show it to me.

**Comment by tdasto** [comment]
This appears to require a yum update on the Guest computers b/c cannot duplicate on other computers.

**Comment by sharkbit** [comment]
Needs testing removed javascript errors on that page

**Comment by sharkbit** [comment]
After talking with Jenn, we are closing the ticket.  RSO's aren't complaining.

**Comment by tdasto** [comment]
When BH logs in and goes to store, the App **does** load the BH data. However, his Guest wants to buy a target and the BH clicks the Guest checkbox. The badge number does go to 9999 and can't be edited - all good so far! Except, the first and last name populate automatically with info from a former guest. These fields should remain blank for the Guest to enter his info.
