### ISSUE TITLE
Issue New Badge with Friends Help

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#125]
What does the checkbox labeled "Friends help?" do on the Issue new range badge page, payment form?

**Comment by sharkbit** [comment]
It allows you to use a '"Friends" work hour credits  to help pay for your badge.

**Comment by tdasto** [comment]
I don't think it works.

**Comment by sharkbit** [comment]
to test on tmp,  create new badge,  then use friend badge 6903,  tadaa.  
Friend must have available credits from the appropriate year.

**Comment by tdasto** [comment]
It only works if a Badge Type is chosen before the Friend Help checkbox is checked. Therefore, the checkbox needs to be hidden until 'badge_fee'<>"". So, I tried to use your display:none code but did not work. I tried it two different ways.
