### ISSUE TITLE
Recurring Start Date

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#13]
Upon entering a recurring event today requires the event to start immediately at the next defined recurring date/time. I tried entering an event that recurs on the 1st Sunday of every 1 month but does not start until January 2021. (I'm a planner) I did select 1/2/2021 start date and it only took the 1/2 date. 
The App found 1 conflict (7/5/2020)- does this mean that there are no other conflicts or was this just the 1st one the App found? -  and does not allow me to create the recurring event.
Take a look at Conflicted Events. I also do not get the Approve Event hyperlink in this tab. 
![Conflicte_Recurrig](https://user-images.githubusercontent.com/67211480/85486730-38746f80-b599-11ea-81a7-d92b10520b5c.PNG)

**Comment by tdasto** [comment]
Good work, Marc!

**Comment by sharkbit** [comment]
Per Our Conversation: 
- The event start and stop dates can be in order (Jan 15 - Jul 21) or over a Season (Sep 1 - Mar 1).
- Events will never be created for a Past Date. 

- To create an event scheduled every month, starting in three months, you can use (Sep 1 -  Aug 30) to trick the system and then correct the start & stop dates once the date has passed.

**Comment by tdasto** [comment]
I tried your example of tricking the system using the same dates. See event "Recurring Start Date Test". App created an Aug 2020 event which according to you it was not supposed to do. Then if it created that Aug event why did it not create the July event? I understand why it did not create the Jan-June events.
