### ISSUE TITLE
cannot print

### ISSUE THREAD

**Issue by JennMart** [sharkbit/BadgeApp#135]
Mpdf\MpdfException: Temporary files directory "/.../vendor/mpdf/mpdf/src/Config/../../tmp/mpdf" is not writable in /.../vendor/mpdf/mpdf/src/Cache.php:21
Stack trace:
#0 /.../vendor/mpdf/mpdf/src/ServiceFactory.php(61): Mpdf\Cache->__construct()
#1 /.../vendor/mpdf/mpdf/src/Mpdf.php(1064): Mpdf\ServiceFactory->getServices()
#2 /.../backend/controllers/BadgesController.php(891): Mpdf\Mpdf->__construct()
#3 [internal function]: backend\controllers\BadgesController->actionPrint()
#4 /.../vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#5 /.../vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#6 /.../vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction()
#7 /.../vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction()
#8 /.../vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest()
#9 /.../backend/web/index.php(17): yii\base\Application->run()
#10 {main}

**Comment by sharkbit** [comment]
Forgot to update the Permissions of the Directory after updating Composer
