### ISSUE TITLE
Remove CIO Priv...Click Update...Crash

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#136]
in_array() expects parameter 2 to be array, string given

 in blah/controllers/AccountsController.php      at Line 92

**Comment by sharkbit** [comment]
what page was this on?  accounts/update?  Why are we removing the CIO check instead of fixing it?

**Comment by tdasto** [comment]
Go to Admin, Auth Users, choose a CIO, remove CIO priv, then click update and see the crash... I do not understand your last question.

**Comment by sharkbit** [comment]
Should be fixed
