### ISSUE TITLE
searching for certification

### ISSUE THREAD

**Issue by JennMart** [sharkbit/BadgeApp#137]
When I try to add a certification it just keeps searching and searching and locks up, not allowing me to continue.

**Comment by sharkbit** [comment]
I turned that function off for now,  what was the badge number

**Comment by JennMart** [comment]
badge 8724
He paid for his steel cert online with order 8118 and I gave him the 
card.  He showed me his passing score on his phone.

---
Jennifer Martucci
Office Manager
Associated Gun Clubs of Baltimore
410-461-8532 Office
officemgr@agcrange.org
www.agcrange.org

**Comment by sharkbit** [comment]
Fixed with 8b2419d & 5845ad0
