### ISSUE TITLE
store purchases

### ISSUE THREAD

**Issue by JennMart** [sharkbit/BadgeApp#139]
Make store purchases like post print transactions

- add salesperson
- add time?

**Comment by sharkbit** [comment]
@JennMart Just pushed a big update to the Store / Purchases tabs.  Please take a look

**Comment by JennMart** [comment]
When I tried to export it says it can't do it to excel and when I tried 
pdf I got this
  PHP Fatal Error – yii\base\ErrorException
Allowed memory size of 134217728 bytes exhausted (tried to allocate 
81920 bytes)

The salesperson will be useful for sure.

---
Jennifer Martucci
Office Manager
Associated Gun Clubs of Baltimore
410-461-8532 Office
officemgr@agcrange.org
www.agcrange.org

**Comment by sharkbit** [comment]
I should really limit that page,  try adding a year or year & month,  you just tried to export the hole table...

**Comment by JennMart** [comment]
That makes sense, I wasn't thinking about that.  It works great except I 
can't get either of the excel ones to work.  Looks good, thanks.

---
Jennifer Martucci
Office Manager
Associated Gun Clubs of Baltimore
410-461-8532 Office
officemgr@agcrange.org
www.agcrange.org

**Comment by sharkbit** [comment]
@tdasto can you try to export using excel,  they both work for me.

badgeApp -> Sales -> Purchases,  Filter by year  (2021) then try exporting as excel.

**Comment by sharkbit** [comment]
Export as cvs and pdf work well so closing.
