### ISSUE TITLE
Event Show/No-Show

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#14]
Currently, the RSOs report on clubs that show/no-show to their scheduled events. It would be a great enhancement to allow the RSOs to get into the App and click either an "Attended" checkbox or a Show/No-Show dropdown menu.

**Comment by sharkbit** [comment]
In the calendar (calendar.agc)?  or Events (BadgeApp.agc)?

**Comment by tdasto** [comment]
I was originally thinking Calendar App but one day they will be one!

**Comment by sharkbit** [comment]
GTG
