### ISSUE TITLE
Add Shooting Bay Privilege

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#141]
Due to a Policy change, we need to add a Shooting Bay privilege to the App. Only three clubs have permission to use the bays and others are trying to add events there. 

Is this going to be a problem?

**Comment by sharkbit** [comment]
Shooting Bay should have access to delete and edit all of those types of events.

**Comment by t7731mg** [comment]
Just put an entry on the calendar for ARPC for Thursday 4/15 from 7 - 9 pm. I am unable to delete or edit that entry or any other entry on the calendar except for those for AGC Action Shooting.

I am not trying to delete this entry, however am using this as an example.

Thank you

**Comment by sharkbit** [comment]
The 'Shooting Bay' Privilege now has access to edit and delete Shooting Bay calendar events.
