### ISSUE TITLE
Conflicted Events Warning

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#142]
Make the Conflicted Events tab red when such events are created.

**Comment by sharkbit** [comment]
Notes while at work

`
use backend\models\AgcCal;

$testConflict=0;
if(yii::$app->controller->hasPermission('calendar/conflict')) {
	if(yii::$app->controller->hasPermission('calendar/all')) {
		$testConflict = (new AgcCal)::find()->where(['conflict' => 1])->count();
	} else {
		$testConflict = (new AgcCal)::find()->where(['conflict' => 1])
		->andWhere(['in','agc_calendar.club_id',json_decode(Yii::$app->user->identity->clubs)])
		->count();
	}
}
echo "Conflicts found: ".$testConflict;

if ($testConflict > 0);
?>

<style="color:red">glyphicon glyphicon-warning-sign </style>`

**Comment by sharkbit** [comment]
Updated!  looks annoying!

**Comment by tdasto** [comment]
I was almost there. I had the code to change the tab color and was trying to figure out the conflict=1 call when I had to get to bed. I then woke up this morning realizing how to do it. You obviously did it and was close to what I was thinking. However, I would have never figured out "json_decode(Yii::$app->user->identity->clubs)" in the Where line. I think it looks good!

**Comment by tdasto** [comment]
I left comment on the issue.

**Comment by tdasto** [comment]
Ummm, your fix is not working properly. It shows flashing Conflict tab when there are no conflicts...

**Comment by sharkbit** [comment]
if you want to work on it you can add the line below to help troubleshoot, in the php section around line 19.  

`echo "# of Conflicts found: ". $testConflict`
