### ISSUE TITLE
Color-code Red Class 4 Rules

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#143]
RSOs would like the Class 4 rules colored in red text to help differentiate from similarly-worded lower class violations.

**Comment by sharkbit** [comment]
Where?  in index,  ok we can do that,  in dropdown, ugg

**Comment by tdasto** [comment]
Let me do the simple stuff

**Comment by sharkbit** [comment]
Still didnt answer the question? A, B, or both.
A.  in  the index.
B.  in the DropDown
