### ISSUE TITLE
Single, annual, recurring events do not work. 

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#15]
Error flag pops up stating "No events will be created. Check your dates!"

**Comment by sharkbit** [comment]
@tdasto I have adjusted the rollover date to 06-01,  July we will need to set it back to 07-06.

./controllers/CalendarController.php: 71
./controllers/CalendarController.php:274:
./views/calendar/index.php:172:

**Comment by sharkbit** [comment]
Events will not be created for past dates, even Recurring Events.  After 1 Jul events will be able to reserve the next calendar year.

**Comment by sharkbit** [comment]
Dates are now hard coded to 07-01, fixed in https://github.com/sharkbit/BadgeApp/commit/fcac9a92ec2ee5cb87ca1287d2ced033d6bbbed3#diff-bbf219334d86cc77ef746204d128a076

**Comment by tdasto** [comment]
Attempted to create a yearly recurring event on the 3rd Thursday in September. Crashed with the following information on the screen;

Start DGetEventDates: Start: 2020-01-01 20:20:00, End: 2020-12-31 20:20:00, Pat: {"yearly":"day","every":"1","on":"third","day":"thu","of":"9"}, yr: 2020
Yr: 2020
Start: 2020-01-01 = 1577836800,
Stop: 2020-12-31 = 1609372800,
Direction: N. Pattern: {"yearly":"day","every":"1","on":"third","day":"thu","of":"9"}
stdClass Object ( [yearly] => day [every] => 1 [on] => third [day] => thu [of] => 9 )
yearly
2020-09-17GetEventDates: Start: 2020-01-01 20:20:00, End: 2020-12-31 20:20:00, Pat: {"yearly":"day","every":"1","on":"third","day":"thu","of":"9"}, yr: 2021
Yr: 2021
Start: 2021-01-01 = 1609459200,
Stop: 2021-12-31 = 1640908800,
Direction: N. Pattern: {"yearly":"day","every":"1","on":"third","day":"thu","of":"9"}
stdClass Object ( [yearly] => day [every] => 1 [on] => third [day] => thu [of] => 9 )
yearly
2021-09-16

**Comment by sharkbit** [comment]
This should be fixed by https://github.com/sharkbit/BadgeApp/commit/80d8278d8130b5f45f75b507fe311f09ec4d8faa#diff-bbf219334d86cc77ef746204d128a076

I think you caught this in the middle of a change. or you were on tmp,  that is my Sanity Check if you can believe it.
