### ISSUE TITLE
New Sales Report page

### ISSUE THREAD

**Issue by JennMart** [sharkbit/BadgeApp#151]
All clubs are being recorded as APL upon renewal.

**Comment by JennMart** [comment]
It looks like the clubs are being recorded properly but when you go to  Post/Print transactions in the Admin menu it is still listing them all as APL.  This is where I pull the reports from.

**Comment by sharkbit** [comment]
That makes more sense.  Do we still need that page? 

- Can we migrate to the Sales page?
- What other info would you need on the sails page to make P.P.T. go away?

 Will look at the P.P.T. page this evening.

**Comment by sharkbit** [comment]
Removed Club from P.P.T., Still think we should move / modify the sales purchases page as it has all the data we need.

**Comment by JennMart** [comment]
I pull reports monthly from the post/print transactions page.  I use the 
reports in excel to show number of badge sales, renewal, and 
certification and sort those per club.  I also use monthly reports 
showing guests per month and CIO students per month (which is not a 
simple report to pull as far as I can tell).

---
Jennifer Martucci
Office Manager
Associated Gun Clubs of Baltimore
410-461-8532 Office
officemgr@agcrange.org
www.agcrange.org

**Comment by sharkbit** [comment]
No comments in a while, I good.
