### ISSUE TITLE
Recurring Event Ending 1 week Early

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#157]
I can't figure out why Recurring Event Master Record 53563 is ending on 10/5/21 instead of on 10/12/21 as defined. Original recurring end date was 10/15 which is the Friday past the actual end date. I changed to 10/12 and republished but that did not fix it. 
Asking for a friend.

**Comment by sharkbit** [comment]
Thinking it's on [CalendarController.php#L766](https://github.com/sharkbit/BadgeApp/blob/master/backend/controllers/CalendarController.php#L766 ) . Might need a <= vice <
