### ISSUE TITLE
Add Additional Event Type - Rescheduled

### ISSUE THREAD

**Issue by t7731mg** [sharkbit/BadgeApp#159]
Would like to see an additional Event Type "Rescheduled" added to the Calendar module that would mirror "Cancelled" - Oftentimes we reschedule an event for later in the month and would like to see that appear on the Calendar instead of Cancelled.

**Comment by sharkbit** [comment]
@tdasto @pagcrange   Agree / Disagree?
- No code changes needed, 
- DB update would work, 
- Currently no way to add new event types via App as any user.

**Comment by pagcrange** [comment]
???

*Andrew Pelton*

*(443) 300-6360*

*President, Baltimore Rifle Club*

*President, **Associated Gun Clubs of Baltimore, Inc.*

**Comment by t7731mg** [comment]
It's nothing Andrew.  I asked for an upgrade to the calendar and I think
this is just Tom and Marc discussing how to handle it.

**Comment by tdasto** [comment]
Mike is right and made me laugh with his reply...
I have been AWOL on App issues with Marc and have two issues to discuss
with him.
Our schedules seem to align less during the warmer months!

Marc - if the Rescheduled type does not have to point to the rescheduled
event, then this seems to be an easy item to complete. By Assigning the
Issue #159 to me, are you asking/telling me to program/add it to the App?

**Comment by sharkbit** [comment]
Database Updated,  AGC main website needed a little code update, and created a new Flag 
![flag_rescheduled](https://user-images.githubusercontent.com/979670/126078634-4e39f480-0d46-455a-8d1f-545d1eddaed3.png)
