### ISSUE TITLE
Add Discount Note box 

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#161]
Management wants a text box added to the .../badge/create page near the Discounts box to be able to specify the reason for the discount.

**Comment by sharkbit** [comment]
> Management wants a text box added to the .../badge/create page near the Discounts box to be able to specify the reason for the discount.

@pagcrange  Isn't the Only reason someone can get a discount on badges work hours?   I though that field was read only.

**Comment by tdasto** [comment]
No, there are many circumstances but the Student discount is in policy
already and has been for years.

**Comment by sharkbit** [comment]
to make this easier, I think it should be and Extra,  then Click on type of discount, Allowing them to type in random thinks was always problematic in my view.

**Comment by tdasto** [comment]
Ok, I can propose a list of options later.

**Comment by tdasto** [comment]
They want to track Student Discounts from CIOs. So, I'm thinking a dropdown
list containing;

all CIOs
Work Credit
Other

I can't think of any other categories but Other covers a wide range of odd
situations.

Tom

**Comment by sharkbit** [comment]
DB Updates were needed as well.
