### ISSUE TITLE
Easy way to delete Multiple Conflicted Events

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#162]
The rollover process leaves 300+ events in the Conflicted Events tab. These are mostly semi-weekly air rifle practices by ARPC and SRRPC. Deleting one at a time is unreasonable.

Do we just do this through Workbench?

Still, it would be better for the clubs to do it but with so many it won't get done.

**Comment by sharkbit** [comment]
How about a 'Delete All' Button up by the 'Create Event' button that is only displayed on the Conflicts tab.  Would also need an 'Are you really Really Sure' java popup before executing some SQL to mark their Conflicting records as Deleted.

**Comment by tdasto** [comment]
That is a better idea than mine...

**Comment by sharkbit** [comment]
The button gets pretty complicated as soon as the person has access to 'All' Clubs.  will probably deny the button if they have access to see all the clubs.

**Comment by tdasto** [comment]
Got it. Good idea!

**Comment by tdasto** [comment]
Did you do any work on this in one of your branches?

**Comment by tdasto** [comment]
Cool that you got the checkbox in the filter, but try to filter another field before clicking the checkbox. I tried to enter ARPC as the sponsor...crashed.

**Comment by sharkbit** [comment]
It should be good

**Comment by tdasto** [comment]
Trying to filter on Event Type or Range Status or Active. These filters reset immediately and do not allow filter. The Event Name and the Facility filters work.

**Comment by sharkbit** [comment]
Filters are working Much better! with less code!  is it done yet?

**Comment by sharkbit** [comment]
22a47fd2edd08cb4c7cec4cacce863875626cc22  forgot to add the comment to the code

**Comment by tdasto** [comment]
Looks good. Should we incorporate the new code in other areas?

**Comment by sharkbit** [comment]
Branch has been merged to master and deleted
