### ISSUE TITLE
Republishing is being misused

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#163]
See email. Event created somehow and then Republished to over ride a Monthly event somehow. I really have no idea how it happened but Republishing cannot work current year events.

**Comment by tdasto** [comment]
I used TMP. Modifying Tom seemed too complex.

The code to do this looked simple enough (even though I don't fully understand the language).

When trying to edit a current-year event and then Check Availability, I get a weird list of info but still cannot Update.
![image](https://user-images.githubusercontent.com/67211480/166177133-c4c9d7b4-5d03-4b37-81a6-aee651ce617d.png)

That could just be a TMP thing? Other than that, seems to work fine.

**Comment by sharkbit** [comment]
Seems I forgot to disable some testing notifications...

**Comment by sharkbit** [comment]
Pushed!
