### ISSUE TITLE
extras not recording properly

### ISSUE THREAD

**Issue by JennMart** [sharkbit/BadgeApp#168]
When extra items are added to a badge sale in the issue new badge or renewal screen the specific items are not showing up in the purchase records, only the total amount of the sale listed as a badge sale.

**Comment by sharkbit** [comment]
@JennMart @tdasto   I just pushed two updates that will record Cart Items properly in the BadgeApp.  How should we record badge discounts?  
- my thought would be to use the full badge price and add a new item 'Discount-reason' - $$$
- I noticed we do it differently depending on where in the app it is processed.
