### ISSUE TITLE
Add Last Renewal Date to Quarterly Roster

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#176]
I will modify the report to include the last Renewal Date. Right now, the AGC does not require that the AGC Clubs annually report club membership of their Life and 15-Yr BHs. Therefore, all these badges show up as Approved in the database. I've suggested that we automatically change the status of these badges on February 1st to Suspended if they have not renewed by the end of the grace period (1/31/yyyy). The January quarterly report showing active BHs is a bit misleading since we give BHs a grace period to renew through 1/31/yyyy, thus, these BHs show up as Approved in the report. I see how adding the Renewal Date could help.

**Comment by tdasto** [comment]
Considering that the next quarterly report comes out next week, can we review this code I did either Sunday night or Monday evening?

**Comment by sharkbit** [comment]
I dont think the Last Renewal date is pulling the correct data?  did you run the report and verify the data / date expected?

**Comment by sharkbit** [comment]
I dont think the Last Renewal date is pulling the correct data?  did you run the report and verify the data / date expected?

**Comment by sharkbit** [comment]
Code is  ba65e52 & e27df6c
