### ISSUE TITLE
Sales Tax

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#177]
Management wants to add Sales Tax to non-fee related products. The OM will provide SKUs that do not need Sales Tax.

**Comment by sharkbit** [comment]
Aren't there different Sales Taxes for different types of items.  Need to talk about it to understand more.

**Comment by sharkbit** [comment]
@tdasto  12 Hours of coding.   All transactions check for sales tax (Except for Certificates)  want to review this as it touched 13 files with 100 lines of code.

**Comment by sharkbit** [comment]
Hopefully no issues
