### ISSUE TITLE
Inventory Kits

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#178]
Need a new item category for Kits;
-  Kits contain several inventoried items,
-  Item count of kit will be # of kits it can make with current inventory.

**Comment by tdasto** [comment]
"Item count of kit will be # of kits it can make with current inventory."
That is not the way to keep inventory. Instead, when a kit is sold, each item in the kit is decremented from stock.

**Comment by sharkbit** [comment]
Done!
