### ISSUE TITLE
Range Point Limit Exceeded

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#18]
I stumbled upon a bug regard lane limits. I was able to schedule a monthly, 3rd Wed, recurring event on the 200 with a 10-lane reservation. However, in August that range has a 2-lane reservation already in the calendar (Range Status Open).  The recurring event should not have been created or it should have dumped that month to the Conflicts tab.

**Comment by sharkbit** [comment]
Invalid, not enough data
