### ISSUE TITLE
Multiple identical Recurring Events

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#19]
I can't explain this problem any other way. The Action Shooting Chair is trying to use the Calendar App and now we have multiple identical recurring events. Go look at the Recurring Event Tab. Sort on Facility and review Shooting Bay 2 recurring events for the event Outlaw Steel Challenge Match Set Up. The correct one goes from 0800 to 1700. I could easily delete the others but I wanted you to see this and try to figure out how one could create multiple recurring events that are the same.

**Comment by sharkbit** [comment]
The events were from the same master event?  I don't know what he did.  I republished the master and it fixed it,  

I'm guessing he edited a single event of the series and changed it to a different day with an event of that series already there...  

Will Look into it.  If editing a series and not master, verify not overwriting another event in series.

**Comment by sharkbit** [comment]
Didnt close it right again...
