### ISSUE TITLE
Broke Tmp on Recurring Event

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#20]
In TMP, try creating a recurring event. Broke. Not sure you can see the cut-and-past error image below. Just try creating a recurring event.

![image](https://user-images.githubusercontent.com/67211480/85966459-dbf4c400-b98d-11ea-8745-7d4a4b9096cb.png)
 
![image](https://user-images.githubusercontent.com/67211480/85966507-fe86dd00-b98d-11ea-9a05-eb763847d268.png)

**Comment by tdasto** [comment]
I don't know what happened but I was able to create a recurring event later...

**Comment by sharkbit** [comment]
you didn't select all the proper widgets when making the recurring event,  what was the patter you entered or "Thought you entered"
![image](https://user-images.githubusercontent.com/979670/86018590-90750100-b9f3-11ea-9a3b-f56da690934a.png)

**Comment by sharkbit** [comment]
added default choices when changing radio buttons
