### ISSUE TITLE
First of the Month causing Recurring week Plus One

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#21]
OK, these titles suck,

Try to create a recurring event for the 3rd Wed of the month in TMP. The App creates the event on July 22 which is the **4th Wed**. See Calendar ID 44883. In August it is correctly on the **3rd Wed**. The 1st of the month falling on a Wed in July is causing an error. The Action Chair noticed this too but I did not say anything because I did not re-create it until now...by accident. I was trying to show you a lane count limit example.

**Comment by sharkbit** [comment]
This is a PHP bug!  please go vote for this issue at:
https://bugs.php.net/bug.php?id=77999&edit=3

**Comment by tdasto** [comment]
I voted. Should we vote daily?

**Comment by sharkbit** [comment]
Added a check for the bug to work around it.  It will keep working even if the fix the bug.

**Comment by tdasto** [comment]
I was going to mention that it is working now! Great work!
