### ISSUE TITLE
Delineate New from Renew

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#215]
In the Store Purchases report, indicate New from Renew on badge sales.

**Comment by sharkbit** [comment]
Where?

**Comment by tdasto** [comment]
Let me worry about this...

**Comment by sharkbit** [comment]
Looks like we are already storing the info in the subscriptions table,  just have it called out in the SQL on the Clubs Report page.

https://github.com/sharkbit/BadgeApp/blob/0af7380c3d9c97da40908807d9df4e4ddebe0844/backend/controllers/BadgesController.php#L592

and 
https://github.com/sharkbit/BadgeApp/blob/0af7380c3d9c97da40908807d9df4e4ddebe0844/backend/controllers/BadgesController.php#L1063
