### ISSUE TITLE
Guest Pay Switch-a-Roo

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#218]
Hard to explain...Summarizing - BH Badge# changed to Jennifer's when she went into edit a Guest entry prior to PayNowCash being clicked. Here were the Steps...
1 - Guest was registered with App and selected to make a cash payment
2 - After entered, Guest realized they did not have the cash
3 - RSO rang up a Store CC purchase and then told Jennifer later
4 - Jennifer clicked the pencil icon to edit the Guest entry
5 - Changed the dropdown to PayNow and clicked Update
6 - On Visitor Log BH Badge# changed to Jennifer's Badge#

I'm going into the database and change it back to the correct BH Badge#

**Comment by sharkbit** [comment]
I remember some one mentioning this,  but on one put in a ticket!  :)
