### ISSUE TITLE
Guest PayNowCash Incorrect Accounting

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#219]
Two Guests were registered under BH with payment option as Cash but clicking PayNowCash in log on first Guest was $20 but 2nd Guest was not marked paid and still had PayNowCash in log. Clicking 2nd Guest showed a payment due of $10. So, instead of a $20 payment for two Guests it now shows as $30.

**Comment by sharkbit** [comment]
I see an issue where the RSO just goes to the Store page and clicks guest badge,  then system will not know what member badge to credit so it should not let him do that...

**Comment by sharkbit** [comment]
Log all the things correctly...
