### ISSUE TITLE
Guest Charges Incorrect

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#224]
There is some issue when people are checking in guests where the system charges them for one more guest than they actually have.  I think it is on the add visitor screen when they choose a shooter count other than 1, they then put in the first guest and then subsequent guests and it seems to charge them for the number they entered and then additionally for each subsequent guest separately even though it only registers the correct number of guests in the guest count.  It would probably be easiest to have them just enter each guest individually which is the work around we've been using.  If we did away with the shooter count field as an option on that screen they would just be forced to do one at a time.

**Comment by sharkbit** [comment]
guest checkout will only let you but 2 guests??

**Comment by sharkbit** [comment]
Fixed and pushed
