### ISSUE TITLE
Work Credit Bug

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#227]
If I understand it correctly, it appears that when an RSO or salesperson
renews a badge that has work credits, the record then shows that
saleasperson under the created by and authorized by columns rather than
whoever was originally the actual creator or person to auhorize the
credits.

**Comment by sharkbit** [comment]
When a badge is renewed a new negative work credit is created for that badge.  That entry will have the sales person listed for the created by & supervisor entries.  

The badges original work credits do not get modified.
