### ISSUE TITLE
Event Conflict Not on Start/End Time

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#23]
Issue Title Sucks.
Event in calendar already from 9AM-2PM, say MH. Entering a new event that starts at 2PM in MH should not cause "Range is Closed due to other event". 

Solution might be to automatically internally adjust all End times to one minute less and all Start times to one minute more.

**Comment by sharkbit** [comment]
This should be fixed,  I adjusted the search to +/- one minute for the start and stop times so that events can start and stop on the hour.
