### ISSUE TITLE
Error screen when I click on Club Sales

### ISSUE THREAD

**Issue by JennMart** [sharkbit/BadgeApp#231]
PDOException
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 200' at line 1

    1. in /var/www/badgeApp/vendor/yiisoft/yii2/db/Command.php at line 1177
    1168116911701171117211731174117511761177117811791180118111821183118411851186

                $this->internalExecute($rawSql);
     
                if ($method === '') {
                    $result = new DataReader($this);
                } else {
                    if ($fetchMode === null) {
                        $fetchMode = $this->fetchMode;
                    }
                    $result = call_user_func_array([$this->pdoStatement, $method], (array) $fetchMode);
                    $this->pdoStatement->closeCursor();
                }
     
                $profile and Yii::endProfile($rawSql, 'yii\db\Command::query');
            } catch (Exception $e) {
                $profile and Yii::endProfile($rawSql, 'yii\db\Command::query');
                throw $e;
            }
     
            if (isset($cache, $cacheKey, $info)) {

    2. in /var/www/badgeApp/vendor/yiisoft/yii2/db/Command.php at line 1177 – PDOStatement::closeCursor()
    3. in /var/www/badgeApp/vendor/yiisoft/yii2/db/Command.php at line 410 – [yii\db\Command::queryInternal](http://www.yiiframework.com/doc-2.0/yii-db-command.html#queryInternal()-detail)()
    4. in /var/www/badgeApp/vendor/yiisoft/yii2/data/SqlDataProvider.php at line 137 – [yii\db\Command::queryAll](http://www.yiiframework.com/doc-2.0/yii-db-command.html#queryAll()-detail)()
    5. in /var/www/badgeApp/vendor/yiisoft/yii2/data/BaseDataProvider.php at line 101 – [yii\data\SqlDataProvider::prepareModels](http://www.yiiframework.com/doc-2.0/yii-data-sqldataprovider.html#prepareModels()-detail)()
    6. in /var/www/badgeApp/vendor/yiisoft/yii2/data/BaseDataProvider.php at line 114 – [yii\data\BaseDataProvider::prepare](http://www.yiiframework.com/doc-2.0/yii-data-basedataprovider.html#prepare()-detail)()
    7. in /var/www/badgeApp/vendor/kartik-v/yii2-export/src/ExportMenu.php at line 1831 – [yii\data\BaseDataProvider::getModels](http://www.yiiframework.com/doc-2.0/yii-data-basedataprovider.html#getModels()-detail)()
    1825182618271828182918301831183218331834183518361837

                $model = $modelClass::instance();
     
                return $model->getAttributeLabel($attribute);
            } elseif ($provider instanceof ActiveDataProvider && $provider->query instanceof QueryInterface) {
                return Inflector::camel2words($attribute);
            } else {
                $models = $provider->getModels();
                if (($model = reset($models)) instanceof Model) {
                    return $model->getAttributeLabel($attribute);
                } else {
                    return Inflector::camel2words($attribute);
                }
            }

    8. in /var/www/badgeApp/vendor/kartik-v/yii2-export/src/ExportMenu.php at line 1800 – kartik\export\ExportMenu::getAttributeLabel()
    1794179517961797179817991800180118021803180418051806

            $label = Yii::t('kvexport', 'Column').' '.$key;
            if (isset($column->label)) {
                $label = $column->label;
            } elseif (isset($column->header)) {
                $label = $column->header;
            } elseif (isset($column->attribute)) {
                $label = $this->getAttributeLabel($column->attribute);
            } elseif (!$column instanceof DataColumn) {
                $class = explode('\\', get_class($column));
                $label = Inflector::camel2words(end($class));
            }
     
            return trim(strip_tags(str_replace(['<br>', '<br/>'], ' ', $label)));

    9. in /var/www/badgeApp/vendor/kartik-v/yii2-export/src/ExportMenu.php at line 1774 – kartik\export\ExportMenu::getColumnLabel()
    1768176917701771177217731774177517761777177817791780

                    'aria-haspopup' => 'true',
                    'aria-expanded' => 'false',
                ],
                $this->columnSelectorOptions
            );
            foreach ($this->columns as $key => $column) {
                $selector[$key] = $this->getColumnLabel($key, $column);
            }
            $this->columnSelector = array_replace($selector, $this->columnSelector);
            if (!isset($this->selectedColumns)) {
                $keys = array_keys($this->columnSelector);
                $this->selectedColumns = array_combine($keys, $keys);
            }

    10. in /var/www/badgeApp/vendor/kartik-v/yii2-export/src/ExportMenu.php at line 755 – kartik\export\ExportMenu::initColumnSelector()
    749750751752753754755756757758759760761

        /**
         * @inheritdoc
         */
        public function run()
        {
            $this->initI18N(__DIR__);
            $this->initColumnSelector();
            $this->setVisibleColumns();
            $this->initExport();
            if (!$this->_triggerDownload) {
                $this->registerAssets();
                echo $this->renderExportMenu();
     

    11. in /var/www/badgeApp/vendor/yiisoft/yii2/base/Widget.php at line 146 – kartik\export\ExportMenu::run()
    12. in /var/www/badgeApp/backend/views/sales/report.php at line 93 – [yii\base\Widget::widget](http://www.yiiframework.com/doc-2.0/yii-base-widget.html#widget()-detail)()
    87888990919293949596979899

            <div class="col-sm-6">
            <?= $SalesReport->getSRdata($SalesReport->created_at) ?>
            </div>
            <div class="col-sm-6 pull-right">
            Export Data -
            <?=ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'columns' => $gridColumns,
                'fontAwesome' => true,
                'batchSize' => 0,
                'filename'=>  $this->title,
                'target' => '_blank',
                'folder' => '@webroot/export', // this is default save folder on server

    13. in /var/www/badgeApp/vendor/yiisoft/yii2/base/View.php at line 347 – require('/var/www/badgeApp/backend/views/...')
    14. in /var/www/badgeApp/vendor/yiisoft/yii2/base/View.php at line 257 – [yii\base\View::renderPhpFile](http://www.yiiframework.com/doc-2.0/yii-base-view.html#renderPhpFile()-detail)()
    15. in /var/www/badgeApp/vendor/yiisoft/yii2/base/View.php at line 156 – [yii\base\View::renderFile](http://www.yiiframework.com/doc-2.0/yii-base-view.html#renderFile()-detail)()
    16. in /var/www/badgeApp/vendor/yiisoft/yii2/base/Controller.php at line 407 – [yii\base\View::render](http://www.yiiframework.com/doc-2.0/yii-base-view.html#render()-detail)()
    17. in /var/www/badgeApp/backend/controllers/SalesController.php at line 211 – [yii\base\Controller::render](http://www.yiiframework.com/doc-2.0/yii-base-controller.html#render()-detail)()
    205206207208209210211212213214215216217

            if(isset($_REQUEST['SalesReport']['created_at'])) {
                $SalesReport->created_at = $_REQUEST['SalesReport']['created_at'];
            } else {
                $SalesReport->created_at = date('m/01/Y',strtotime(yii::$app->controller->getNowTime())).' - '.date('m/t/Y',strtotime(yii::$app->controller->getNowTime()));
            }
            return $this->render('report',[
                'SalesReport' => $SalesReport,
            ]);
        }
     
        public function actionStock() {
            $searchModel = new StoreItemsSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    18. backend\controllers\SalesController::actionReport()
    19. in /var/www/badgeApp/vendor/yiisoft/yii2/base/InlineAction.php at line 57 – call_user_func_array()
    20. in /var/www/badgeApp/vendor/yiisoft/yii2/base/Controller.php at line 178 – [yii\base\InlineAction::runWithParams](http://www.yiiframework.com/doc-2.0/yii-base-inlineaction.html#runWithParams()-detail)()
    21. in /var/www/badgeApp/vendor/yiisoft/yii2/base/Module.php at line 552 – [yii\base\Controller::runAction](http://www.yiiframework.com/doc-2.0/yii-base-controller.html#runAction()-detail)()
    22. in /var/www/badgeApp/vendor/yiisoft/yii2/web/Application.php at line 103 – [yii\base\Module::runAction](http://www.yiiframework.com/doc-2.0/yii-base-module.html#runAction()-detail)()
    23. in /var/www/badgeApp/vendor/yiisoft/yii2/base/Application.php at line 384 – [yii\web\Application::handleRequest](http://www.yiiframework.com/doc-2.0/yii-web-application.html#handleRequest()-detail)()
    24. in /var/www/badgeApp/backend/web/index.php at line 17 – [yii\base\Application::run](http://www.yiiframework.com/doc-2.0/yii-base-application.html#run()-detail)()
    11121314151617

        require(__DIR__ . '/../../common/config/main.php'),
        require(__DIR__ . '/../../common/config/main-local.php'),
        require(__DIR__ . '/../config/main.php'),
        require(__DIR__ . '/../config/main-local.php')
    );
     
    (new yii\web\Application($config))->run();

$_COOKIE = [
    'advanced-backend' => 'u13f3hs925q2sn2b3rrfn27j14',
    '_csrf-backend' => '432e7236a090290a29808b8c78cf8f77664388fd4016f96e11fb344b1793b36da:2:{i:0;s:13:"_csrf-backend";i:1;s:32:"Jcqa-HVimDbELKHM7KAsoyjQxoYA6z0A";}',
];

$_SESSION = [
    '__flash' => [],
    'badge_number' => 6392,
    'user' => 'Jennifer Martucci',
    'names' =>

**Comment by sharkbit** [comment]
Found the Issue,  YII changed the way the handle custom SQL statements by adding Limit 200 the the end.  my statement was already closed with a ';'
