### ISSUE TITLE
Retire Stickers on New badge year sale date

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#236]

**Comment by sharkbit** [comment]
Make a ? Button / Function to auto retire all old stickers after new badge sales date passes.
 - Where should this pop up?
 - Needs user interaction?  or just runs when date passes?

`update  BadgeDB.sticker set 'status'='ret' where sticker like '2022-%' and 'status'!='isu' ;`

**Comment by sharkbit** [comment]
You can already Retire Stickers on the RSO Report -> Stickers Page using the 'Move Stickers' button.  
Do we need to do more?

**Comment by tdasto** [comment]
I don't think automatic is the answer. There may be a past year issue that
involves 2022 badges - like a BH buying badge online back in August and not
picking it up until November/December.
Retiring stickers could be automatic on January 1st. But then the App would
need to allow 2022 sticker selection through December 31st.

**Comment by sharkbit** [comment]
Stickers can be manually retired / moved in groups or one at a time on the RSO -> Sticker page.
