### ISSUE TITLE
Calendar Filter Not Working

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#237]
Select a date range of 12/4/22-12/4/22 and Search. Events are listed properly but notice that Active filter is set to No and Approved filter is set to False. Try to enter any other filter and you get No results found. The filter is not working.

**Comment by sharkbit** [comment]
Is this still a thing?    Did you want it to default to active and approved = true?  I haven't found an error.   

Updates may have fixed it.

**Comment by tdasto** [comment]
Looks like the server update fixed this problem. Filters working and defaults look good.
