### ISSUE TITLE
Editing Store Stck prices Breaks the Real Badge App

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#24]
https://badgeapp.agcrange.org/sales/stock?page=2

Clicking on the pen icon on this page breaks the app. Just try it and break it yourself to see the error.

I suppose this is not the way to update the prices. I was trying to update the half-year prices.

**Comment by sharkbit** [comment]
teh Update Item page has been fixed, but Family badge prices are still being calculated instead of pulling from store price.

**Comment by sharkbit** [comment]
Closing issue will auto close project item
