### ISSUE TITLE
New Work Credits are not registering

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#240]

**Comment by tdasto** [comment]
Work credits are not registering. I added a Work Credit for a BH and Created it  but the table does not show the BH. I was expecting to see his name in the table with the Approval Needed link to click...

**Comment by sharkbit** [comment]
well this is interesting,  I see the 2 you created & the one I created,  but they are not displaying in the App...

**Comment by sharkbit** [comment]
we just forgot how Work credits works...
