### ISSUE TITLE
Gender Switch w/o Surgery

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#246]
There is at least one issue going on with the gender field.  We've
noticed a lot of male badge holders now show as female.  I'm not sure
why or if it is multiple issues.  It seems like one thing is when you
add a certification to a badge it somehow changes their gender to
female.  I haven't issued any certificates to females recently so I
don't know if it would change them to male or not.

**Comment by sharkbit** [comment]
Haven't seen any more after code updates
