### ISSUE TITLE
Can't Leave Class Blank

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#25]
Did you know that when you click on a grayed-out box and then click on the box you really wanted to enter data, a text warning pops up stating that you cannot leave the "field" blank. For example, go to https://tmp.agcrange.org/violations/create and click on the Class field. Then click on another non-gray box as if you were to enter data. 

Doesn't break. So is this a bug?

I'm logged in as #24.

**Comment by sharkbit** [comment]
Patch will remove field from required list and will not care if it's blank since it is automatically filled in.
