### ISSUE TITLE
Delete Cert Crash

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#260]
I was asked to delete a holster cert from 7955. From the BH Certifications page I clicked on the trash can for the holster cert and received the following warning. The cert was deleted successfully.

![Image](https://github.com/sharkbit/BadgeApp/assets/67211480/6a64b4c4-8168-4dcf-9ba5-1b1992039309)

**Comment by sharkbit** [comment]
Fixed!
