### ISSUE TITLE
No Calendar Events

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#27]
I'm logged in as #24.

Go to Calendar Beta. No events listed. #24 is AGC Staff and he does the Orientation Walk-Thrus. Needs calendar access.

**Comment by sharkbit** [comment]
Is this still an issue?  On Tmp Gave him RSO, Calendar Coordinator, Chairman.  think this will work.

**Comment by sharkbit** [comment]
Closing issue will auto close project item
