### ISSUE TITLE
AGC Staff and Closed Range Status

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#28]
Is it possible to allow AGC Staff to enter events with a "Closed" Range Status?

AGC Staff are the Chairs like High Power Chair, Pistol Chair, Action Shooting Chair...

**Comment by sharkbit** [comment]
Yes Just give that access the 'calendar/close' permission in admin control.  do you want this user by user or to a cretin level?  Admin, rso?

With permissions no rebuilt i can add a permission level with just that?

**Comment by tdasto** [comment]
I do not know what a "cretin level" is?

**Comment by sharkbit** [comment]
Closing issue will auto close project item
