### ISSUE TITLE
Broke upon creating new user

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#29]
Logged in as admin.d'asto
Tried to create a new RSO user.
Upon hitting the create button the App broke.
![image](https://user-images.githubusercontent.com/67211480/86308344-f1b0f600-bbe6-11ea-95d5-d1cc146c8682.png)
![image](https://user-images.githubusercontent.com/67211480/86308364-02fa0280-bbe7-11ea-9595-10a3ef332074.png)
![image](https://user-images.githubusercontent.com/67211480/86308394-17d69600-bbe7-11ea-8a3b-9b66c78839ad.png)

**Comment by sharkbit** [comment]
Closing issue will auto close project item
