### ISSUE TITLE
Mark Steinacker #24 Calendar Entry

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#30]
A few items to note here, see image;

1. Mark created "AGC Orientation" in the Trap Room. Notice on the same day and time is another recurring event for the same activity. I'm pointing out that the Sponsors are different. I'm not sure if Walk-about is new with these new permissions but if it is, then all AGC Orientation events need to be updated.

2. He chose the Trap Room but the Range Status is Open and should automatically be Closed. 

3. When creating a new event, please make the default Yes for Active

![image](https://user-images.githubusercontent.com/67211480/86309507-ef03d000-bbe9-11ea-9308-2bb3a46f97b1.png)

**Comment by tdasto** [comment]
The only item remaining on this issue is all "[wildcard] Orientations" by AGC Staff would need to have sponsor changed to "Walk-about". We can do this after you push out the new permissions to Calendar App

**Comment by sharkbit** [comment]
Closing issue will auto close project item
