### ISSUE TITLE
New Club Created but not in Calendar List

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#31]
See new club #53; https://tmp.agcrange.org/clubs/index?sort=-club_id

https://tmp.agcrange.org/cal-setup/clubs
Should show the new club I created.

**Comment by sharkbit** [comment]
Your New Great Club shows up in the Club Calendar drop down and in the Club Badge drop down.

The Cal-setup Club page is showing the Old Club Roster from the old app,  it is meant for migration purposes only.
