### ISSUE TITLE
Remove Prices from 'Fee Schedule' in favor of store prices

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#32]
Ref #24 need to remove prices from 'Fee Schedule ' and rename button.
- then force prices from store.  
- Verify create and renew badges are pulling right prices.

**Comment by sharkbit** [comment]
Almost done,  just need to redo fee structure for badge types.   Ugg

**Comment by sharkbit** [comment]
This should be good,  need to test Creating new different types of users, and renewing different types of users.

**Comment by tdasto** [comment]
Broke on the first try. See email reply b/c I was told to never paste the full address on github.

**Comment by sharkbit** [comment]
OK, we are ready for another round of testing.
