### ISSUE TITLE
Quarterly Club Roster Automation

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#33]
On the firs day of the new Quarter (1/1, 4/1, 7/1, 10/1), the App automatically emails Club Rosters to each club. Right now I have to remember to click a button.

**Comment by sharkbit** [comment]
To work from the BadgeApp it will have to be after moving to Verizon, otherwise it should be a cronjob on the calendar server.

**Comment by sharkbit** [comment]
fixed see email
