### ISSUE TITLE
Infraction = Suspension?

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#35]
Marc - email from RSO Lead... (only Class 4 violations s/b suspended);

Tom, in the last couple of weeks I have recorded a class 2 violation (I.C.3.d) that resulted in the BH's status being changed to Suspended. in both cases, Tia and Jennifer were able to change the status back to Approved. 

I don't know why this is happening -- can you shed any light on this? 

Jim
Range Safety Officer
Associated Gun Clubs of Baltimore, Inc.

**Comment by sharkbit** [comment]
Working as designed,  He needs glasses.  There are two IC03.d one is a class 2, one is a class 4.
![image](https://user-images.githubusercontent.com/979670/86798996-6ea4fb00-c03f-11ea-87d6-d78eab1658f0.png)
