### ISSUE TITLE
Unauthorized (#401) error - Edit Series 

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#36]
tmp.agcrange.org
I created a new Authorized User, B4692 (new Chairman, RSO, CIO) - yeh!
Logged in as B4692
Clicked on AGC Range Badge Processing recurring event (Event ID 41392) on 7/12/20. 
Clicked on Edit the Series.
Then decided to not do anything and clicked on the "Calendar" hyper link (https://tmp.agcrange.org/calendar/index). 
Unauthorized (#401) error.

Turns out I could repeat this on any recurring event.

**Comment by sharkbit** [comment]
RSO & CIO do not have access to recurring events.  I added it to Chairman.
- Are we still chaining the name of Chairman to Calendar Close?

**Comment by tdasto** [comment]
Or just "Close Range" or "Close". Admins just have to know what it means.

**Comment by sharkbit** [comment]
Closing issue will auto close project item
