### ISSUE TITLE
Permission Ranking (Chairman, RSO, CIO)

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#37]
I logged in on TMP as B4692 (Chair, RSO, CIO). Remember, I am good at breaking shit.

Because B4692 had CIO privileges (as well as Chair and RSO), B4692 was not able to create a recurring event. Although we currently do not have a BH who is all three (Chair, RSO, CIO), it is possible. I think Chair and RSO are higher rank than CIO which should allow person to create recurring events. My two cents...

**Comment by tdasto** [comment]
So, sounds like if you just change name from Chair to Close it would make more sense. So, I can give a Calendar Coordinator the Close option to allow them to close range events.

**Comment by sharkbit** [comment]
Same issue https://github.com/sharkbit/BadgeApp/issues/36
