### ISSUE TITLE
Publish to Next Year -- Double listing of Recurring event

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#38]
Weird thing it only created a single event in the calendar but listed double recurring events. I just deleted the extra recurring event.

**Comment by sharkbit** [comment]
Added a Disable to the button once clicked.  should fix it.

**Comment by tdasto** [comment]
Not true...on TMP

Go to the Recurring Event page and click on a Publish to Next Year link. Then, come back to the Recurring Event page and you will see of that same recurring event.

**Comment by sharkbit** [comment]
Should be Working Now!
