### ISSUE TITLE
Calendar: One Event on Multiple Ranges?

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#4]
Can we make it so that one event can use multiple ranges.  Just like clubs?

**Comment by sharkbit** [comment]
This is working well,  but i need events with multiple ranges to do more testing.  
-This currently breaks forced rollover.

**Comment by tdasto** [comment]
Awesome stuff. This is what I found so far, **minor** as it is.
1) Cannot filter events. If a multi-range event has the 200-yd range in the array, I cannot see the event when I select the 200-yd range in the Facility drop down filter.
2) Range "status" note after "Check Availability" does not list ranges in a logical order

**Comment by sharkbit** [comment]
1. Calendar Facility filter fixed,
2. They are in an Order (By id),  I updated the good/bad coloring.  Is that good enough, or do i need to figure out ordering?
