### ISSUE TITLE
Conflict where no Conflict exists

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#40]
I should be able to create this recurring annual event but cannot due to an apparent conflict (error).
![image](https://user-images.githubusercontent.com/67211480/86801897-7c0fb480-c042-11ea-8e91-af6da1ad192e.png)

I'm not "killing you". There are just a few bugs related to recurring events that are similar.

**Comment by sharkbit** [comment]
Should be fixed,  you can now specify what date.  This specific fix has been pushed to calendar already.
