### ISSUE TITLE
Force Recurring Events by Priority

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#48]
Based on Priority,  Yearly, Monthly , Weekly, Daily

**Comment by tdasto** [comment]
The following three events have the highest priority;
New Year’s Day, CLOSED ALL DAY
Thanksgiving Day, CLOSED AT 2:00 pm
Christmas Day, CLOSED ALL DAY

Master Record 48485 has two conflicts on the calendar; T-giving & X-mas. [AGC Range Badge Processing, M-F, all year long]

**Comment by sharkbit** [comment]
What about non recurring events?  I'm trying to think of a priority order. 

- Same level will not overwrite each other,
- Lower number has priority,

1. Yearly,
2. Monthly,
3. Weekly,
4. Daily,
5. Non recurring.

**Comment by tdasto** [comment]
I think I disagree. Theoretically, if we could get the database corrected for all existing recurring events, then an existing non-recurring event would have a higher priority against any new recurring event trying to be created. If we took 2020 as the standard for recurring events, then those events would have to deal with the priority you defined. But, new recurring events would only be created if they did not cause a conflict with existing non-recurring and recurring events.

Corrected list;
1. Holiday Closing
2. Yearly,
3. Monthly
4. Weekly
5. Daily

**Comment by sharkbit** [comment]
You know there is no recurring time frame of Holiday right?   You left off Non-recurring events priority?  Maybe a new field that means "No Override"?
