### ISSUE TITLE
 No club acronyms or club names are allowed in the event title.

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#5]
Calendar/_form:  No club acronyms or club names are allowed in the event title.  Probably done with JavaScript On Change.

Create a list of acronyms/names/name_versions that are not allowed in the Event title and your program can make sure that none of the items in the list are in the title.

**Comment by tdasto** [comment]
APL Gun Club 
Arlington Rifle & Pistol Club 
Baltimore Rifle Club 
Berwyn Rod & Gun Club 
Catonsville Scouters 
Chesapeake Rifle & Pistol Club 
Gadsden Pew Club 
Garrison Rifle & Revolver Club 
Givati Rifle & Pistol Club 
Glenmore Rifle & Pistol Club 
Goddard Sportsman Club 
Greenbelt Gun Club 
Homewood Rifle & Pistol Club 
Howard County Rifle & Pistol Club 
Marriottsville Metallic Silhouette Shooters 
Marriottsville Muzzle Loaders 
Maryland Rifle Club 
Maryland Shall Issue 
Maryland State Rifle and Pistol Association 
Maryland Tenth Cavalry Gun Club 
Maryland Thompson Collectors Association 
Meade Rifle and Pistol Club 
Meade Rod & Gun Club 
Monumental Rifle & Pistol Club 
Mount Washington Rod and Gun Club 
Northrop Grumman Westinghouse Shooting Sports Club 
Old Post Rifle and Pistol Club 
Pioneer Rod & Gun Club 
Stemmers Run Rifle & Pistol Club 
Stoney Creek Fishing & Hunting Club 
APL 
AGC 
Arlington 
ARPC 
Baltimore 
BRC 
Berwyn 
BRGC 
Catonsville 
CS 
Cheasapeake 
CRPC 
GPC 
Gadsden 
GRRC 
Garrison 
Givati 
GRPC 
Glenmore 
Goddard 
GSC 
NASA 
GGC 
Greenbelt 
HRPC 
Homewood 
HCRPC 
Howard County 
MMSS 
Marriottsville 
MML 
MRC 
Maryland 
MSI 
MSRPA 
Tenth Cav 
MTCGC 
MRPC 
Meade 
MRGC 
Monumental 
Mount Washington 
MWRGC 
Mt Washington 
NGWSSC 
Northrop 
Northrop Grumman 
Westinghouse 
OPRPC 
Old Post 
OP 
Pioneer 
PRGC 
Stemmers 
SRRPC 
Stoney Creek 
SCFHC

**Comment by sharkbit** [comment]
Acronyms, easy, will not be allowed.

Club Names gets really complicated;
- Full Club mane exact match?  what if the leave out on word?
- Ban any wood in their name?  then the cant use And, Club, Rifle, Pistol, and others. 
++ Maybe if a word from that list is found they get a warning but are still able to create the event?

**Comment by sharkbit** [comment]
Now provides a warning,  but still lets then create the event.  White listed a few words on line 68

**Comment by tdasto** [comment]
ARPC was allowed but Arlington was not. Half right.
