### ISSUE TITLE
New $calendarPermission & $cioPermission Range Status Permissions

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#50]
Please change $calendarPermission and $cioPermission to only have one option for Range Status and that would be Open.

I was going to be fancy and do a pull request, make the change myself, then request your verification...but I ran out of time today.

**Comment by sharkbit** [comment]
If the only have one Option do they need to see this field?

**Comment by tdasto** [comment]
@sharkbit Nope

**Comment by sharkbit** [comment]
What About Chairman?

**Comment by sharkbit** [comment]
Root, Admin, & Chairman get Range Status all others set to open
fixed in https://github.com/sharkbit/BadgeApp/commit/c26eeb9de3745ce3501e1e9ba195103503dfba46
