### ISSUE TITLE
Annual Recurring and Duplication error

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#52]
This is related to #21 and the duplication bugs.

On TMP, I just created an annual event, for FBG, on the 3rd Sat of August. The first Sat is August 1st. The App created two events on the 15th of 2020 and one event on the 21st 2021 (3rd Sat, correct)

I did it again, for Stoney Creek, for the 3rd Thur of Oct. Same result.

The duplication is the only error, but it is due to the event occurring on the same day as the 1st of the month falls on.

**Comment by sharkbit** [comment]
Not really related but in the same code.  Fixed none the less.
