### ISSUE TITLE
CIO and Club Calendar Coord

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#53]
So, we have RSOs that are CIOs and we have RSOs that are Calendar Coordinators/Chairmen. Now, I find out that we have a CIO that is a Club Calendar Coordinator!

How is this a problem? Well, all CIO events have Event Type =  CIO Course. The higher privilege of Calendar Coord allows the CIO to enter other types of Event Types for their CIO events. 

I'm really sorry, Marc. But, my only suggestion is to force those entering events to select the Sponsor type first (if they have multiple calendars in their permissions) and if the Sponsor type is a CIO then limit the Event Type to CIO Course.

**Comment by tdasto** [comment]
On TMP.

Now RSO and Calendar Coord, 02 50 24 24 only has Event Status options of Canceled and CIO Course. B24 is not a CIO. B24 is the Walk Through Chairman (Walk-Thru Cal Coord) and also a RSO. His options for Event Status are at least Public.

**Comment by sharkbit** [comment]
The Clubs are currently set as ether an 'AGC Club' or 'CIO'.  So in practices 'AGC Walk' is thought of as a CIO event.   

1. Should 'Chairman' override this and allow any status?
2. Should 'Chairman' have access to use 'Board of Trustees Invitation ' & 'Executive Committee Invitation'

**Comment by tdasto** [comment]
We are starting to get into a hodge-podge way of programming that will lead
to hidden bugs and more problems.

Chairman was developed to allow special people a Range Status of Closed.

The simplest way to do it, all calendars not a CIO calendar are AGC Clubs
calendars. So, CIOs will only see CIO Course or Canceled as their Event
Status options and all other users who have "Calendar Access" <> (not set)
can have all the other Event Status options except CIO Course.

If you are going down a path that can divvy up the Event Status options to
users with different user privileges,  then I would recommend the following:
*CIOs -*
CIO Course
Canceled

*Club Calendar Coordinators -*
Members
Members and Guests
Private Event
Public
Youth
Women
Canceled

*Admin & Root -*
all of them

**Comment by sharkbit** [comment]
Fixed with https://github.com/sharkbit/BadgeApp/commit/1b703dd027ccf01926a0c76eab8a9c41e4dc7176
