### ISSUE TITLE
Fix User Privilege search

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#56]

**Comment by sharkbit** [comment]
Fixed with cool MySQL JSON Search in yii2!

**Comment by tdasto** [comment]
Works on TMP.

Crashes on Calendar, let me know if you need the error.

**Comment by sharkbit** [comment]
We need to update the version of Maria DB we are using,  and It's not Easy...  we need version 10.3 and are running 10.0, you have to uninstall and the install the next version up to the desired.   They have 10.4 should we just go up to that?

**Comment by sharkbit** [comment]
Removing temp fix as Database Upgrades are done. https://github.com/sharkbit/BadgeApp/commit/24a64f006597d7069df9f6f0445a623a23959978
