### ISSUE TITLE
Visitor Log Link

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#58]
If you clicked the button image below in the Badge App, it used to take you to the Visitor's Log page.

![image](https://user-images.githubusercontent.com/67211480/87863869-6ba6e600-c92e-11ea-9510-9d52d074dd30.png)

**Comment by sharkbit** [comment]
That was never a button or  a link.  if you want it to take you to he guest page instead of clicking the guest button i can do that but it's a little redundant.
