### ISSUE TITLE
Fee Schedule for Holster

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#6]
Fee Schedule was updated for Holster to $30 but the renewing/certification page is still pulling in $20.

**Comment by sharkbit** [comment]
This should be changed on the intuit Quick books Online then pulled in the store with 'Pull Inventory', but it looks like that broke.  So I am manually setting it for now in the database.

in /sales/inventory
```
QuickBooksOnline\API\Exception\SdkException
The OAuth 2 Access Token is not set in the Access Token Object.


6. in /var/www/agc/backend/views/payment/_inventory.php at line 4 – QuickBooksOnline\API\DataService\DataService::Query()
12345678910

<?php
use backend\models\StoreItems;
 
    $QueryAll = $dataService->Query('SELECT * FROM Item'); // where Type ="Inventory"');
    $error = $dataService->getLastError();
    if ($error) {
```

**Comment by sharkbit** [comment]
Fixed,  long term pricing update is https://github.com/sharkbit/BadgeApp/issues/32
