### ISSUE TITLE
PHP Error when processing credit cards

### ISSUE THREAD

**Issue by THyatt1** [sharkbit/BadgeApp#62]
Received PHP error when attempting to process credit card for badge sales. Member received an error message when paying for guest via credit card. However, the transaction processed through our merchant account.

**Comment by sharkbit** [comment]
Unfortunately this was caused by horrendous network latency.  I will look into making the error display better.

**Comment by sharkbit** [comment]
This should work much better now that we have moved off Intuit.  https://github.com/sharkbit/BadgeApp/issues/64
