### ISSUE TITLE
RSO, Cal Coord, Privileges Combining

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#65]
Sent this to Marc Steinacker 02 50 24: 
It seems that when we try to add one new feature we create a bug somewhere else. A special case; an RSO, A Calendar Coordinator, and a Chairman. These privileges are causing a conflict of sorts. The RSO privilege allows you to see all the events. The Calendar Coordinator allows you to add/edit/delete Walk-Thru calendar events. The privileges are combining and you can now edit all events!

**Comment by sharkbit** [comment]
fixed
