### ISSUE TITLE
Calendar Broke: Monumental WDMM Republish to Next Year

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#66]
When I tried to Republish to Next Year the WDMM recurring event, I broke the app...

Database Exception – yii\db\Exception
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's Division Monthly Meeting', keywords='WDMM', recur_week_days='{"monthly":"da...' at line 1
The SQL being executed was: UPDATE associat_agcnew.agc_calendar SET club_id=20, event_name='Women's Division Monthly Meeting', keywords='WDMM', recur_week_days='{"monthly":"day","when":"third","day":"sunday","every":"1"}' WHERE recurrent_calendar_id = 49224
Error Info: Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's Division Monthly Meeting', keywords='WDMM', recur_week_days='{"monthly":"da...' at line 1
)

**Comment by sharkbit** [comment]
Did you update the record first?  That should fix any issues, but I will update this to Update the Record First, then Republish, from the republish button.

**Comment by tdasto** [comment]
I can't remember on this specific one or not but I know that I was trying to follow the Check Availability-Update-Check Availability-Republish sequence on all of the events.

**Comment by sharkbit** [comment]
Fixed
