### ISSUE TITLE
Weekly MH Tues-Th not Allowed

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#70]
Not being allowed to create Weekly MH Tues-Th event b/c Monumental has MH Weekly (ID 51423) but only on Mon and Fri. It should allow the recurring event. I just tried to make the new event a Monthly event the 1st Tuesday of the month and it won't let it happen but it should work.

**Comment by sharkbit** [comment]
sounds like an event is on the wrong date.  is the mon fri event reqlly on mon & fri?

**Comment by sharkbit** [comment]
Umm....   (id 51950)

**Comment by tdasto** [comment]
No I had the event correct, 51423, was stopping me from entering an event. Here is another attempt; 51996 is a Tues & Th event and it is stopping me from making a M & F event.

![image](https://user-images.githubusercontent.com/67211480/88988028-b8cb7600-d2a5-11ea-901f-8bdef7b7ca85.png)

**Comment by sharkbit** [comment]
So I looked at 51996 and it was on a 2021-01-14 (a Monday). I republished the master and now 52140 is on Tuesday  so maybe a check to verify the original date is within the scope of the recurring dates and pattern.
