### ISSUE TITLE
Successfully Entered Yearly but got Error, too.

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#74]

**Comment by sharkbit** [comment]
-Bet you cant replicate this....  Just pushed code,  and was probably in the middle of it.   Make sure your issues are able to be duplicated on tmp.
- Also Delete the image, NO Full URL's.  you can use paint to "white out" the full url if you want to keep it.

**Comment by sharkbit** [comment]
fixed https://github.com/sharkbit/BadgeApp/commit/4ffca29f806dae0226237b693e4d1fc55d9677af it didn't like forcing a check of form on load.
