### ISSUE TITLE
Sponsor s/b REAL club name

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#76]
So, I edited the Shortname field in the clubs index to include several options for abbreviations, as you suggested. Now, this field is showing up in the Sponsor field when listing events. I recommend changing to Club Name.

**Comment by sharkbit** [comment]
Short names are used in a lot more places that that one spot,  do we need to make another field on Clubs to deal with dirty words?

**Comment by tdasto** [comment]
Might have to. I noticed that you use the shortname on the popup tables for range conflicts.

**Comment by tdasto** [comment]
Am I supposed to do anything with the "Avoid" Column? A lot are not set...

**Comment by sharkbit** [comment]
Does it need a better name?  You only need something there if it's not covered by the Club Name or Short Name.
