### ISSUE TITLE
Canceled Event Type cancels the Closed Range Status

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#8]
If a club cancels an event that is a Range Status of Closed, then that single event no longer keeps other events from using that range in that day/time slot. The Canceled Event Type allows the Event to show up on the website with a Canceled flag. So, we cannot delete the event or inactive the event since the clubs use the website calendar to "notify" members of a canceled event.

**Comment by sharkbit** [comment]
Can we make it turn a Closed range to Open once canceled?   Seems like the best solution.

**Comment by tdasto** [comment]
That only works if making that change effects the current-year event and not future events if it is a recurring event.

**Comment by sharkbit** [comment]
They would only affect that event.  
- Unless the event is the Master Recurring Record. 
I will work on the following:
** If editing Master record from index, only update that record,  if updating from recurring update series.

**Comment by sharkbit** [comment]
If you set an Event Status as Canceled it forces the Range Status to Open.  [fix here](https://github.com/sharkbit/BadgeApp/commit/07a489e18dc0602cc62f25f2301ed253ea59b104l)

**Comment by tdasto** [comment]
This works, but I have a suggestion. The pop-up text reads, "Facility might be in use" and the pop-up table shows the Range Status as Open.  I think it would make more sense to the User if the pop-up table also showed Event Type which in this case would read "Canceled" and/or change the text.

**Comment by sharkbit** [comment]
Closing issue will auto close project item
