### ISSUE TITLE
Multi-Range not catching some conflicts

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#80]
I could not determine what was causing this. I'll check it out on TMP but twice during conversion from multi-events to single event/multi-range the added ranges were not caught as a conflict.

**Comment by sharkbit** [comment]
How do you know there were actually conflicts?  where are the screenshots or data?

**Comment by sharkbit** [comment]
Ready to test on tmp.

**Comment by tdasto** [comment]
Try to combine these 3 ARPC recurring events into one event by using the event with Trap 1 as the starting point. When you add Trap 2, the app should tell you it is not available and popup the event in a window. It doesn't.

![image](https://user-images.githubusercontent.com/67211480/89722692-9ed31700-d9ba-11ea-898e-db51f26f80b3.png)

**Comment by sharkbit** [comment]
So it does tell you that Trap 1's event (2021-03-01) is on the wrong day.  while trap 2 and 3 are on (2021-03-06).  republishing that event would correct it then there will be duplicates.
