### ISSUE TITLE
Self-Serve Range Badge Kiosk

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#84]
New Club Member:
A) Uses kiosk (dedicated range badge laptop) to 
   1. enter all personal data, 
   2. completes the [Range Orientation Affidavit](https://agcrange.org/agc/pdfs/2015%20AGC%20Affidavit%20Rev%20060115.pdf) in the app (instructor has to swipe their own badge to "sign" the affidavit), 
   3. pay, 
   4. take photo, 
   5. and print badge.

B) Sees Cashier showing his Club Membership card (and pays cash if needed).
C) Cashier verifies all info and applies yearly sticker.

Renewing Club Member:
A) Uses kiosk to verify data and make payment
B) Sees Cashier
C) Cashier verifies all info and applies yearly sticker

**Comment by sharkbit** [comment]
This is working!  but needs a LOT of testing!
- it affected creating and updating all badges,  lots of code changes!

Testing needed:
- create self-registered badge
- take photo

As Admin
- run through Creating new badge (of different types)
- update old badges (of different types)

Let me know what you think @pagcrange @tdasto 
- This is currently live on tmp.

**Comment by tdasto** [comment]
Crashed. 
New User filled out form and submitted fine.
Admin logged in and tried to Update after correcting zip code.
"BadgeController not found?
Badge model, line 161.

**Comment by tdasto** [comment]
Suggestion: limit club selection to the 32 clubs. I was able to pick Associated Club Staff, ZOD.

**Comment by tdasto** [comment]
I was not able to upload a new image for the new member

**Comment by sharkbit** [comment]
Database change needed to limit club list,  add a column for self-register.

Should we allow image upload or Only Camera?

**Comment by pagcrange** [comment]
Camera only,  Otherwise I'm uploading this image as my own.
[image: image.png]

*Andrew Pelton*

*(443) 300-6360*

*President, Baltimore Rifle Club*

*President, **Associated Gun Clubs of Baltimore, Inc.*

**Comment by sharkbit** [comment]
Aww we cant see the image.  Go via email!

**Comment by sharkbit** [comment]
Changes Pushed to tmp,  
- No potion to upload File.
- add Self-register filed to Club table to limit clubs allowed to choose
- fixed saving clubs I hope.

Test and break Again, plz

**Comment by tdasto** [comment]
New Member stuff worked. Email verified. I have some suggestions at the New Member interface level. Save for later after working. 

Logging in as Admin I cannot sell the sticker (Renew Badge not working, no Renewal History) I think you are still working it...

**Comment by sharkbit** [comment]
Ready?

**Comment by pagcrange** [comment]
??

*Andrew Pelton*

*(443) 300-6360*

*President, Baltimore Rifle Club*

*President, **Associated Gun Clubs of Baltimore, Inc.*

**Comment by sharkbit** [comment]
New member Self-Reister has been pushed!
