### ISSUE TITLE
Multi-Clubs Break

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#85]
PHP Deprecated Warning – yii\base\ErrorException
Non-static method backend\controllers\BadgesController::saveClub() should not be called statically

    1. in /home/----/public_html/calendar/backend/controllers/BadgesController.php at line 1336
    1327132813291330133113321333133413351336133713381339134013411342134313441345

            $model->ice_phone = preg_replace('/\D/','',$model->ice_phone);
     
            $model->wt_date = date('Y-m-d',strtotime($model->wt_date));
            $model->expires = date('Y-m-d',strtotime($model->expires));
            $model->incep = date('Y-m-d H:i:s',strtotime($model->incep));
     
            if(isset($model->payment_method)) {
                if($model->payment_method=='creditnow') {$payment_method = 'credit';} else {$payment_method = $model->payment_method;} }
            if(isset($_POST['new_club'])) {
                BadgesController::saveClub($model->badge_number,$_POST['new_club'])

**Comment by sharkbit** [comment]
fixed
