### ISSUE TITLE
Time Stamps on CIO Event posting

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#88]
Tom, today I approved an event for Protective Concepts at ~10:00 and when the wristbands were returned at 11:47 I closed the event. I then noticed that the Approved time and the Closed time were both showing 11:47.

Jim L
Range Safety Officer

**Comment by sharkbit** [comment]
I don't see an issue,  I don't think he really pushed the approved button.  It the event is not approved it will stamp  both approved and closed if the closed button is pushed.
