### ISSUE TITLE
Wrong email verification

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#91]
I received the following email;

I just got this email verification message and wanted to correct your records. I am a lapsed AGC member, but my name is Rachel Szczesiul, not Francis T, so something must have gotten mixed up in your database.

---------- Forwarded message ---------
From: AGC Range <noreply@associatedgunclubs.org>
Date: Fri, Sep 11, 2020, 4:00 PM
Subject: AGC Email Verification
To: Francis T. <rachel.szczesiul@gmail.com>

Hi Francis T.,

Please take a moment to verify your Email by clicking on the link below.

Verify your Email: rachel.szczesiul@gmail.com

Thank You,
Associated Gun Clubs of Baltimore.
https://agcrange.org

P.S. We know our email probably went to the spam folder. Please tell your provider It's not Spam!.

or Click here to remove your email from our List.

**Comment by sharkbit** [comment]
Old Database Issue, not code
