### ISSUE TITLE
Add "Create Store Item'

### ISSUE THREAD

**Issue by sharkbit** [sharkbit/BadgeApp#95]
What's the process for adding products to the Store on the App? Need rental steel, safety glasses, trap ammo. I'd also like to convert the multiple paper target products to one generic option (we have 4 listed but we have about 8 different target types).

**Comment by sharkbit** [comment]
updated

**Comment by tdasto** [comment]
Testing on TMP and I broke it.

![image](https://user-images.githubusercontent.com/67211480/93837421-07691100-fc54-11ea-8f7a-4611f07eef92.png)

**Comment by sharkbit** [comment]
fixed
