### ISSUE TITLE
Create Function to count lanes used

### ISSUE THREAD

**Issue by tdasto** [sharkbit/BadgeApp#96]
Create a function that loops through the event start time to the event end time and counts the lanes reserved by other events by the hour. If the count never reaches the (lane_limit minus lanes_requested) then the range is available.

**Comment by sharkbit** [comment]
https://github.com/sharkbit/BadgeApp/issues/79#issuecomment-686851543 will need to be checked again,  creating this function I validated line 340 is correct as:


https://github.com/sharkbit/BadgeApp/blob/4ece82191f27b936aaa249b2e075138556198327/backend/controllers/CalendarController.php#L340

**Comment by sharkbit** [comment]
Pushed to master and calendar.

**Comment by tdasto** [comment]
#79 worked perfectly

Then test #96 and worked perfectly. Great work!!!
