### ISSUE TITLE
Items Needed To Be Added To APP Store

### ISSUE THREAD

**Issue by THyatt1** [sharkbit/BadgeApp#99]
Could we add the following items to the app STORE:

Under ACTION SHOOTING: Steel Rental $10.00

Under SHOOTING SUPPLIES: Safety Glasses $2.00

Under TRAP: Shot Shells $9.00

**Comment by sharkbit** [comment]
you should be able to do this as an Admin now.   "Admin Functions" -> "Store Items" -> "Create New"!  Let me know if you have any issues.
